version: '3.1'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: api-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: api-spring
    depends_on:
      - db
    ports:
        - "8080:8080"
    networks:
        - app-network

networks:
  app-network:
    driver: bridge