TRUNCATE TABLE medicos;
INSERT INTO medicos (nome, email, crm, especialidade, logradouro, bairro, cep, complemento, numero, uf, cidade) VALUES
                                                                                                                    ('Lucas Almeida Rocha', 'lucas.almeida@saude.com', '87459', 'DERMATOLOGIA', 'Rua dos Jacarandás', 'Bela Vista', '23456-123', 'Casa 7', '320', 'BA', 'Salvador'),
                                                                                                                    ('Carla Dias Gomes', 'carla.dias@saude.com', '65987', 'CARDIOLOGIA', 'Avenida das Palmeiras', 'Nova Esperança', '34567-456', 'Apto 202', '980', 'PE', 'Recife'),
                                                                                                                    ('Rafael Costa Lima', 'rafael.costa@saude.com', '21547', 'GINECOLOGIA', 'Travessa dos Angicos', 'São Cristóvão', '45678-789', 'Bloco C Apto 1501', '150', 'CE', 'Fortaleza'),
                                                                                                                    ('Fernanda Machado Silva', 'fernanda.machado@saude.com', '321654', 'ORTOPEDIA', 'Alameda dos Eucaliptos', 'Jardim Europa', '56789-012', 'Vila 12', '450', 'GO', 'Goiânia'),
                                                                                                                    ('Thiago Nunes Barbosa', 'thiago.nunes@saude.com', '98741', 'DERMATOLOGIA', 'Praça das Orquídeas', 'Vila Mariana', '67890-345', 'Casa 20', '220', 'RS', 'Porto Alegre'),
                                                                                                                    ('Juliana Martins Carvalho', 'juliana.martins@saude.com', '753159', 'CARDIOLOGIA', 'Largo dos Lírios', 'Centro', '78901-678', 'Apto 1104', '1050', 'SC', 'Florianópolis'),
                                                                                                                    ('Bruno Ferreira Cardoso', 'bruno.ferreira@saude.com', '852963', 'GINECOLOGIA', 'Rua das Magnólias', 'Morada do Sol', '89012-901', 'Casa 33', '300', 'MS', 'Campo Grande'),
                                                                                                                    ('Aline Souza Oliveira', 'aline.souza@saude.com', '159753', 'ORTOPEDIA', 'Avenida dos Flamboyants', 'Parque das Nações', '90123-234', 'Casa 19', '120', 'MT', 'Cuiabá'),
                                                                                                                    ('Marcos Ribeiro Faria', 'marcos.ribeiro@saude.com', '456123', 'DERMATOLOGIA', 'Rua dos Pinheiros', 'Vila Olímpia', '01234-567', 'Apto 309', '210', 'SP', 'São Paulo'),
                                                                                                                    ('Patrícia Lima Santos', 'patricia.lima@saude.com', '321456', 'CARDIOLOGIA', 'Estrada das Rosas', 'Campo Belo', '12345-890', 'Casa 27', '500', 'RJ', 'Rio de Janeiro');
