name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: api-db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if CHANGELOG.md was updated
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            if git diff --name-only origin/main..HEAD -- | grep 'CHANGELOG.md'; then
              echo "CHANGELOG.md was updated."
            else
              echo "CHANGELOG.md was not updated. Please update it before merging." && exit 1
            fi
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install

      - name: Test
        run: mvn test